local buffer = vim.api.nvim_get_current_buf()
vim.schedule(function()
  vim.keymap.set("i", "<C-j>", "<plug>CoqNext", { buffer = buffer })
  vim.keymap.set("i", "<C-l>", "<plug>CoqToLine", { buffer = buffer })
  vim.keymap.set("i", "<C-k>", "<plug>CoqUndo", { buffer = buffer })
  vim.keymap.set("n", "<C-j>", "<plug>CoqNext", { buffer = buffer })
  vim.keymap.set("n", "<C-l>", "<plug>CoqToLine", { buffer = buffer })
  vim.keymap.set("n", "<C-k>", "<plug>CoqUndo", { buffer = buffer })
end)
